### ISSUE TITLE
Doesn't work with ASP.NET Web Application (.NET Framework)

### ISSUE THREAD

**Issue by jasek** [paypal/Checkout-NET-SDK#12] opened 2019-02-19 00:38 UTC
Works fine in Console App, .NET Core Web App, but doesn't work in .Net Framework. 
Execution is lost on PayPalHttpClient.Execute. 
It's probably caused by BraintreeHttp.HttpClient
Nevertheless makes this lib impossible to use. 

Recreation steps:
1. Create empty ASP.NET Web Application (.NET Framework) project
2. Try to call client.execute on basic OrdersGetRequest

**Comment by rajarampadmanathan** [comment] 2019-02-19 20:09
Will look into this and get back to you.

**Comment by Enngage** [comment] 2019-02-22 09:14
Are you getting this exception?

`Method not found: 'System.Threading.Tasks.Task1<BraintreeHttp.HttpResponse> BraintreeHttp.HttpClient.Execute(BraintreeHttp.HttpRequest)'.`

If so, I'm having the same issue.

**Comment by jasek** [comment] 2019-02-22 14:05
@Enngage This error pops up if you update BraintreeHttp to version 3.0. It doesn't occur with version 1.5 though but then execution is just lost in creating async dynamic Execute task.

**Comment by Scrambles56** [comment] 2019-02-25 07:05
Also getting this issue... It occasionally executes, but for the most part just gets stuck. Has anyone come up with a solution?

**Comment by Enngage** [comment] 2019-02-25 07:13
I think there are more fundamental problems with PayPal's  API. Since this lib didn't work I tested previous version and eventually created HTTP requests manually only to find out that it doesn't work _most of the times_. API calls that worked 2 days ago stopped working for no apparent reason. The documentation of both this library and REST API is inconsistent and missing a lot of information. I'm really frustrated with PayPal and wish we had more countries supporting Stripe in Europe.

**Comment by Scrambles56** [comment] 2019-02-25 07:29
After a little more investigation into this issue, I can see that in the Console app, outbound network traffic sends the following:
"POST /v1/oauth2/token"  -> 200 response, contains access_token.
then "POST /v2/checkout/orders?" -> 200 response. Execution return back to application.

When running as a Web App, the out bound traffic sends the "POST /v1/oauth2/token" successfully., but never makes a request to "POST /v2/checkout/orders?".

**Comment by pengli29** [comment] 2019-02-25 19:25
@Scrambles56 @jasek 
Could you please let us know which version of the .NET Framework you are using?

**Comment by Scrambles56** [comment] 2019-02-25 20:52
@pengli29 The project that I've been working on is .NET 4.7.2. I found that the issue was with the AuthorizationInjector in the PaypalHttpClient. I have gotten a version of this working by providing the Authorization header prior to calling the Execute method, to prevent the fetchAccessToken method from being called and locking the process.

**Comment by jmmartinezcdo** [comment] 2019-02-25 22:19
I was having a similar issue as @pengli29 , I have also been working on .NET 4.7.2 and the process was hanging without completing. Also resolved it by adding the AccessToken.

**Comment by pengli29** [comment] 2019-02-25 22:25
> @pengli29 The project that I've been working on is .NET 4.7.2. I found that the issue was with the AuthorizationInjector in the PaypalHttpClient. I have gotten a version of this working by providing the Authorization header prior to calling the Execute method, to prevent the fetchAccessToken method from being called and locking the process.

THanks for the Update. 
@jmmartinezcdo @Scrambles56 Have you every tried running with BrainTreeHttp downgraded to version 0.1.5?
Could you please check whether that solved the hanging issue

**Comment by Scrambles56** [comment] 2019-02-25 22:29
@pengli29 I've installed the "PayPalCheckoutSdk (1.0.0)" via nuget, which itself includes the dependency, for "BraintreeHttp-Dotnet (0.1.5)". So when running with this setup, I can confirm that it does hang.

**Comment by jmmartinezcdo** [comment] 2019-02-25 22:42
@pengli29 I can confirm too, it hangs with "BraintreeHttp-Dotnet (0.1.5)".

**Comment by jasek** [comment] 2019-02-25 22:45
Result is the same in all supported .NET Framework versions (up to 4.7.2).
I can confirm that it hangs on resolving OAuth Token.

**Comment by Scrambles56** [comment] 2019-02-25 22:53
It looks like the main PayPal-NET-SDK has a similar issue, 
https://github.com/paypal/PayPal-NET-SDK/issues/360

**Comment by pengli29** [comment] 2019-02-25 23:22
@jasek @Scrambles56 @jmmartinezcdo 
Thank you all for the feedback.
I see two issues in this thread:


- > Method not found: 'System.Threading.Tasks.Task1<BraintreeHttp.HttpResponse> BraintreeHttp.HttpClient.Execute(BraintreeHttp.HttpRequest)'. 

This error happened when using BraintreeHttp-DotNet version 0.3.0

- > Hanging issue when making AccessToken call.




I will start the conversation with the teams to investigate and get them fix asap. Will keep this thread posted.

**Comment by jasek** [comment] 2019-02-25 23:31
@Scrambles56 
I can confirm that this issue is in fact the same one, and workaround provided by @benaadams fix this issue
 ```
      private static async Task<HttpResponse> ExecutePayPalRequest(PayPalHttpClient client, HttpRequest request)
        {
            SynchronizationContext.SetSynchronizationContext(null);
            return await client.Execute(request).ConfigureAwait(false);
        }
```

**Comment by pengli29** [comment] 2019-03-05 04:19
@jasek  @Scrambles56 I am not able to reproduce your issues. Could you please kindly share your sample project or file?

**Comment by snessnes** [comment] 2019-03-05 17:18
I can confirm that the solution provided by @bluepnume works in the following scenario
.NET Framework 4.7.2
PayPalCheckoutSdk 1.0.0
BraintreeHttp-Dotnet 0.1.5 (it does not work in the version 0.3.0)

**Comment by syunakh** [comment] 2019-03-05 17:26
> (it does not work in the version 0.3.0)

rebuilding of the library with BraintreeHttp-Dotnet 0.3.0 fixes the problem

**Comment by jasek** [comment] 2019-03-06 06:19
@s04r Please have a look at this repo 
https://github.com/jasek/PayPalCheckoutSampleProject

**Comment by sjustesen** [comment] 2019-03-16 01:40
I can confirm this is a problem, got it working by using the fix @jasek proposed
https://github.com/paypal/Checkout-NET-SDK/issues/12#issuecomment-467227814

**Comment by 90kay** [comment] 2019-03-19 17:55
@jasek 
Root cause for the `Method not found` issue is because currently our SDK has dependency on `BraintreeHttp-Dotnet 0.1.5`, user upgrading it to 0.3.0 will cause some compatibility issue. 
Please keep using 0.1.5 for now, I will highlight this dependency in documentation and will keep you posted when our SDK change the dependency to 0.3.0

**Comment by Scrambles56** [comment] 2019-04-01 00:59
@pengpeng11 
Has there been any investigation into the the deadlocking that this issue was originally about (the braintree versioning issue wasn't part of the original problem). 
It would be good to not require the workaround found in https://github.com/paypal/Checkout-NET-SDK/issues/12#issuecomment-467227814

**Comment by pengpeng11** [comment] 2019-04-01 17:16
@Scrambles56 
This issue is on our list and we are planning to get it resolved in two weeks. Will keep you posted. Thanks.

**Comment by jannesiera** [comment] 2019-04-10 08:53
Just want to report that I also encountered this issue trying to integrate PayPal in a client's project and my client is waiting for a fix.

**Comment by ManlyBoy** [comment] 2019-04-11 00:12
BraintreeHttp-Dotnet.dll needs to be strongly named for it to work in .Net Framework instances.

Is this dll available as a separate public repository?

**Comment by PrintsCharming** [comment] 2019-05-10 16:45
Any update on this issue?

**Comment by ganeshramc** [comment] 2019-05-10 22:14
Hi @PrintsCharming could you try to use the `develop` branch and see if the issue has been resolved?

**Comment by ManlyBoy** [comment] 2019-05-12 11:23
The thread seems to have been stolen. Is every contributor using .Net or .Net Core?

It's always worked fine for me in .Net Core but I need it to work in .Net 4.7.2.

**Comment by pengli29** [comment] 2019-05-13 21:42
@ManlyBoy could you please try unchecking `Sign this assembly ` in the setting of your project?

**Comment by ManlyBoy** [comment] 2019-05-15 02:21
@pengli29 Didn't make any difference.
For the record. My project is a Web API Targeting .Net Framework 4.7.2. It references the Braintree-DotNet.dll Vesion 0.3.0 included in your latest release. It also references the latest SDK. I'm running it in debug mode in VS2017 current version. Here's the output from Postman:

{
    "Message": "An error has occurred.",
    "ExceptionMessage": "Could not load file or assembly 'BraintreeHttp-Dotnet, Version=0.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)",
    "ExceptionType": "System.IO.FileLoadException",
    "StackTrace": "   at API.Controllers.PayPalController.<GetOrderDetails>d__1.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at API.Controllers.PayPalController.GetOrderDetails(String orderId, Boolean debug)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_3.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"
}

**Comment by mlockett42** [comment] 2019-06-04 08:03
I have what appears to be a similar version of this issue I get the following after use nuget to install the Paypal Checkout SDK

Could not load file or assembly 'System.ValueTuple' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

=== Pre-bind state information ===
LOG: DisplayName = System.ValueTuple
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: System.ValueTuple | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/code/image-chain-web-server/Imagechain.Web/
LOG: Initial PrivatePath = C:\code\image-chain-web-server\Imagechain.Web\bin
Calling assembly : (Unknown).


[FileLoadException: Could not load file or assembly 'System.ValueTuple' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]  [FileLoadException: Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0    System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +37    System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +159    System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +80    System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +22    System.Reflection.Assembly.Load(String assemblyString) +29    System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +38  [ConfigurationErrorsException: Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +726    System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +196    System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +45    System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +172    System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +91    System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +111    System.Web.Compilation.BuildManager.ExecutePreAppStart() +156    System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +695  [HttpException (0x80004005): Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +660    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +188
--


----
Project is running Dotnet framework 4.8 was upgraded from 4.6.1 in an attempt to fix this issue. Similar to other posters it is a Dotnet Framework Web App.

**Comment by ganeshramc** [comment] 2019-06-06 00:17
@mlockett42 we made a fix directly in this repo but it hasn't been released yet. So you might face the same problem when downloading from nuget.

**Comment by ironfly** [comment] 2019-06-20 00:22
Is there any resolution on this?  i have an asp.net site running 4.72 and am simply trying to validate a purchase by orderID - tried all the hacks in this post, no luck.  Not really looking to roll this out to production with these bootstraps anyway.  Does anyone have any tips on possible hitting the rest API directly to do this?

**Comment by ganeshramc** [comment] 2019-06-20 00:37
Hey @ironfly we made a new release and we're going to make another release within the next hour for other purposes. But 1.0.1 should have the changes you wanted.

**Comment by ironfly** [comment] 2019-06-20 15:10
I am simply trying to run this function:

public async static Task<HttpResponse> GetOrder(string orderId, bool debug = false)
    {
      OrdersGetRequest request = new OrdersGetRequest(orderId);
      var response = await PayPalClient.client().Execute(request);
      var result = response.Result<Order>();
     Console.WriteLine("Status: {0}", result.Status);
      return response;
    }
Passing in a valid OrderID, i get nothing out of this.  It does kill our site after running, have to start IIS again.  Any ideas what is going on?  I have the braintreehttp-dotnet dll version 3.0.

Was hoping this would be more straightforward to use, i am simply trying to validate an order created on the client side.  THanks for any advice, kevin

**Comment by pengli29** [comment] 2019-06-20 16:58
@ironfly Hi Kevin, could you please confirm you are using version 1.0.1. if that issue is still there in V 1.0.1, we can set up a conference call to go through the flow to find the root cause. Thanks.

**Comment by ManlyBoy** [comment] 2019-06-21 00:52
@ironfly 
`var response = await PayPalClient.client().Execute(request);` 
Its Client, as in PayPalClient.Client()
I would recommend that you strongly sign BrainlessHttp-DotNet.dll  with ILMerge.
Console writes nowhere in IIS.
Suggest you capture errors in IIS.
If still not working, copy your **exact** code and paste it here.

**Comment by lengc** [comment] 2019-09-26 07:42
In linux, An error happen ‘’ The SSL connection could not be established, see inner exception  ， how to fix this problem

**Comment by existenz69** [comment] 2019-10-31 19:05
Was a solution to this issue ever found, or did everyone give up on it? I'm running SDK 1.0.2. It successfully makes the call to /v2/orders but never returns anything. I've tried the workaround above with no success.

**Comment by gulhakan** [comment] 2020-06-24 16:00
Any update on this issue?

**Closed** 2020-07-28 22:14 UTC
Labels: bug
